config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'employees#index'
  resources :trainings do
    collection do
      get :all
    end
  end
  resources :training_executions do
    member do
      get :register_attendances
      patch :save_attendances
    end
  end
  resources :employees
  resources :companies
  resources :areas
end

app/models/training.rb
class Training < ApplicationRecord
  CATEGORIES = %w[Capacitación Inducción Entrenamiento Otro].freeze
  FILTER_OPTIONS = [
    %w[Categoría category],
    %w[Tema topic],
    %w[Fecha date],
    %w[Área area_id],
    %w[Colaborador collaborator],
    %w[Compañía company_id]
  ].freeze

  has_many :training_executions

  belongs_to :company

  validates :category, presence: true
  validates :topic, presence: true
  validates :objective, presence: true
  validates :date, presence: true
  validates :hourly_intensity, numericality: { greater_than_or_equal_to: 0 }
  validates :trainer, presence: true

  scope :by_category, (->(category) { where('category like ?', "%#{category}%") })
  scope :by_topic, (->(topic) { where('topic like ?', "%#{topic}%") })
  scope :by_date, (->(initial_date, final_date) { where(date: initial_date..final_date) })
  scope :by_area, (->(area_id) { where(area_id: area_id) })
  scope :by_collaborator, (->(collaborator) { where(collaborator_id: Employee.by_name(collaborator).select(:id)) })
  scope :by_company, (->(company_id) { where(company_id: company_id) })

  def self.filter_trainings(params)
    @trainings = Training.all
    @trainings = @trainings.by_category(params[:category]) if params[:category].present?
    @trainings = @trainings.by_topic(params[:topic]) if params[:topic].present?
    @trainings = @trainings.by_date(params[:initial_date].to_time, params[:final_date].to_time) if params[:initial_date].present? && params[:final_date].present?
    @trainings = @trainings.by_area(params[:area_id]) if params[:area_id].present?
    @trainings = @trainings.by_collaborator(params[:collaborator]) if params[:collaborator].present?
    @trainings = @trainings.by_company(params[:company_id]) if params[:company_id].present?
    @trainings
  end

  def to_s
    topic
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    gon.areas = Area.all
    gon.companies = Company.all
    @trainings = Training.filter_trainings(params)
    @trainings = @trainings.paginate(page: params[:page])
  end

  def all
    @trainings = Training.all
    @training_executions = TrainingExecution.all
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @aide = if @training.area_id.present?
              Area.find(@training.area_id)
            elsif @training.collaborator_id.present?
              Employee.find(@training.collaborator_id)
            end
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'La formación ha sido creada exitósamente.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'La formación fue actualizada exitósamente.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'La formación fue eliminada exitósamente.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_training
    @training = Training.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def training_params
    params.require(:training).permit(:category, :topic, :objective, :date, :hourly_intensity, :trainer, :internal, :area_id, :collaborator_id, :company_id)
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_for(training) do |f| %>
  <% if training.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2><%= pluralize(training.errors.count, 'error') %> no permitieron guardar la formación:</h2>

      <ul>
      <% training.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category, 'Tipo' %>
    <%= f.select :category, options_for_select(Training::CATEGORIES, training.category.blank? || Training::CATEGORIES.include?(training.category) ? Training::CATEGORIES[0] : Training::CATEGORIES[3]), {}, class: 'form-control', onchange: 'trainingCategoryChanged()' %>
  </div>

  <div class="form-group" id="category_form_group" style="<%= 'display: none;' if training.category.blank? || Training::CATEGORIES.include?(training.category) %>">
    <%= f.label :category, '¿Cuál?' %>
    <input class="form-control" type="text" value="<%= training.category %>" <%= 'name=training[category]' unless training.category.blank? || Training::CATEGORIES.include?(training.category) %> id="training_category_other">
  </div>

  <div class="form-group">
    <%= f.label :topic, 'Tema' %>
    <%= f.text_field :topic, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :objective, 'Objetivo' %>
    <%= f.text_area :objective, rows: 4, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label style="display: block;">Responsable</label>
    <label class="radio-inline"><input type="radio" name="attendant" onchange="trainingAttendantChanged()" value="area" <%= 'checked' if training.area_id.present? || (training.area_id.blank? && training.collaborator_id.blank?) %>>Área</label>
    <label class="radio-inline"><input type="radio" name="attendant" onchange="trainingAttendantChanged()" value="collaborator" <%= 'checked' if training.collaborator_id.present? %>>Colaborador</label>
  </div>

  <div class="form-group" id="area_form_group" style="<%= 'display: none;' if training.collaborator_id.present? %>">
    <%= f.label :area_id, 'Área responsable' %>
    <%= f.collection_select :area_id, Area.all, :id, :name, { include_blank: 'Seleccionar área...' }, class: 'form-control' %>
  </div>

  <div class="form-group" id="collaborator_form_group" style="<%= 'display: none;' if training.area_id.present? || training.collaborator_id.blank? && training.area_id.blank? %>">
    <%= f.label :area_id, 'Colaborador responsable' %>
    <%= f.collection_select :collaborator_id, Employee.all, :id, :name, { include_blank: 'Seleccionar colaborador...' }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :company_id, 'Compañía' %>
    <%= f.collection_select :company_id, Company.all, :id, :name, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :date, 'Fecha de realización' %>
    <div class="input-group date" id="datetimepicker">
      <%= f.text_field :date, required: true, value: training.date.present? ? training.date.strftime('%d/%m/%y %R') : '', class: 'form-control' %>
      <span class="input-group-addon">
        <%= fa_icon('calendar') %>
      </span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :hourly_intensity, 'Intensidad horaria' %>
    <%= f.number_field :hourly_intensity, min: 0, step: :any, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :trainer, 'Formador' %>
    <%= f.text_field :trainer, required: true, class: 'form-control' %>
  </div>

  <div class="checkbox">
    <%= f.label :internal do %>
      <%= f.check_box :internal %>Interno
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit 'Guardar', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/trainings/all.html.erb
<h1>Formaciones</h1>

<div class="row margin-bottom">
  <div class="col-md-6 col-xs-12">
    <h2>Formaciones planeadas</h2>
    <div class="table-responsive">
      <table class="table table-striped">
        <tbody>
        <% @trainings.each do |training| %>
          <tr>
            <td>
              <p><%= training %> (<%= training.category %>)</p>
              <p><%= training.date.strftime('%d/%m/%y %R') %></p>
            </td>
            <td>
              <span class="pull-right">
                <%= link_to training, class: 'btn btn-info' do %>
                  <%= fa_icon('info') %>
                <% end %>
                <%= link_to edit_training_path(training), class: 'btn btn-warning' do %>
                  <%= fa_icon('pencil') %>
                <% end %>
                <%= link_to training, method: :delete, data: { confirm: '¿Seguro que desea eliminar la formación?' }, class: 'btn btn-danger' do %>
                  <%= fa_icon('trash') %>
                <% end %>
              </span>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-md-6 col-xs-12">
    <h2>Formaciones ejecutadas</h2>
    <div class="table-responsive">
      <table class="table table-striped">
        <tbody>
        <% @training_executions.each do |training_execution| %>
          <tr>
            <td>
              <p><%= training_execution %> (<%= training_execution.category %>)</p>
              <p><%= training_execution.date.strftime('%d/%m/%y %R') %></p>
            </td>
            <td>
              <span class="pull-right">
                <%= link_to training_execution, class: 'btn btn-info' do %>
                  <%= fa_icon('info') %>
                <% end %>
                <%= link_to edit_training_execution_path(training_execution), class: 'btn btn-warning' do %>
                  <%= fa_icon('pencil') %>
                <% end %>
                <%= link_to training_execution, method: :delete, data: { confirm: '¿Seguro que desea eliminar la formación?' }, class: 'btn btn-danger' do %>
                  <%= fa_icon('trash') %>
                <% end %>
              </span>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-xs-12">
    <div class="margin-bottom">
      <%= link_to new_training_path, class: 'btn btn-default' do %>
        <%= fa_icon('plus') %> Formación planeada
      <% end %>
    </div>
    <div class="margin-bottom">
      <%= link_to trainings_path, class: 'btn btn-default' do %>
        <%= fa_icon('eye') %> Planeadas
      <% end %>
    </div>
  </div>
  <div class="col-md-6 col-xs-12">
    <div class="margin-bottom">
      <%= link_to new_training_execution_path, class: 'btn btn-default' do %>
        <%= fa_icon('plus') %> Formación ejecutada
      <% end %>
    </div>
    <div class="margin-bottom">
      <%= link_to training_executions_path, class: 'btn btn-default' do %>
        <%= fa_icon('eye') %> Ejecutadas
      <% end %>
    </div>
  </div>
</div>

app/views/trainings/edit.html.erb
<h1>Editando formación</h1>

<div class="margin-bottom">
  <%= render 'form', training: @training %>
</div>

<%= link_to trainings_path, class: 'btn btn-default' do %>
  <%= fa_icon('arrow-left') %>
<% end %>
<%= link_to @training, class: 'btn btn-info pull-right' do %>
  <%= fa_icon('info') %>
<% end %>

app/views/trainings/index.html.erb
<h1>Formaciones planeadas</h1>

<div class="row">
  <%= form_tag trainings_path, method: :get do %>
    <div class="col-xs-12 col-md-8">
      <div class="form-group" id="filters">
        <%= select_tag :category, options_for_select(Training::CATEGORIES, params[:category].blank? || Training::CATEGORIES.include?(params[:category]) ? params[:category] : Training::CATEGORIES[3]), onchange: 'trainingsFilterCategoryChanged()', class: 'form-control' if params[:filter].blank? || params[:filter] == 'category' %>
        <%= text_field_tag :topic, params[:topic], placeholder: 'Filtrar por...', class: 'form-control' if params[:filter] == 'topic' %>
        <% if params[:filter] == 'date' %>
          <div class="row">
            <div class="col-md-6">
              <div class="input-group date" id="initial-date-picker">
                <%= text_field_tag :initial_date, params[:initial_date], placeholder: 'Fecha inicial', class: 'form-control' %>
                <span class="input-group-addon">
                  <%= fa_icon('calendar') %>
                </span>
              </div>
            </div>
            <div class="col-md-6">
              <div class="input-group date" id="final-date-picker">
                <%= text_field_tag :final_date, params[:final_date], placeholder: 'Fecha final', class: 'form-control' %>
                <span class="input-group-addon">
                  <%= fa_icon('calendar') %>
                </span>
              </div>
            </div>
          </div>
        <% end %>
        <%= select_tag :area_id, options_from_collection_for_select(Area.all, :id, :name, params[:area_id]), class: 'form-control' if params[:filter] == 'area_id' %>
        <%= text_field_tag :collaborator, params[:collaborator], placeholder: 'Filtrar por nombre de colaborador...', class: 'form-control' if params[:filter] == 'collaborator' %>
        <%= select_tag :company_id, options_from_collection_for_select(Company.all, :id, :name, params[:company_id]), class: 'form-control' if params[:filter] == 'company_id' %>
      </div>
      <div class="form-group" id="category_form_group" style="<%= 'display: none;' if params[:category].blank? || Training::CATEGORIES.include?(params[:category]) %>">
        <input class="form-control" type="text" value="<%= params[:category] %>" <%= 'name=category' unless params[:category].blank? || Training::CATEGORIES.include?(params[:category]) %> placeholder="¿Cuál?" id="category_other">
      </div>
    </div>
    <div class="col-xs-12 col-md-3">
      <div class="form-group">
        <%= select_tag :filter, options_for_select(Training::FILTER_OPTIONS, params[:filter]), onchange: 'trainingsFilterChanged()', class: 'form-control' %>
      </div>
    </div>
    <div class="col-xs-12 col-md-1">
      <%= submit_tag 'Filtrar', class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

<div class="table-responsive margin-bottom">
  <table class="table table-striped">
    <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td>
          <p><%= training %> (<%= training.category %>)</p>
          <p><%= training.date.strftime('%d/%m/%y %R') %></p>
        </td>
        <td>
          <span class="pull-right">
            <%= link_to training, class: 'btn btn-info' do %>
              <%= fa_icon('info') %>
            <% end %>
            <%= link_to edit_training_path(training), class: 'btn btn-warning' do %>
              <%= fa_icon('pencil') %>
            <% end %>
            <%= link_to training, method: :delete, data: { confirm: '¿Seguro que desea eliminar la formación?' }, class: 'btn btn-danger' do %>
              <%= fa_icon('trash') %>
            <% end %>
          </span>
        </td>
      </tr>
    <% end %>
    <% if @trainings.empty? %>
      <tr>
        <td>
          No se encontraron registros
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div>
  <%= link_to new_training_path, class: 'btn btn-default' do %>
    <%= fa_icon('plus') %>
  <% end %>

  <%= link_to all_trainings_path, class: 'btn btn-default pull-right' do %>
    <%= fa_icon('eye') %> Todas las formaciones
  <% end %>
</div>

<%= will_paginate @trainings %>

app/views/trainings/new.html.erb
<h1>Nueva formación</h1>

<div class="margin-bottom">
  <%= render 'form', training: @training %>
</div>

<%= link_to trainings_path, class: 'btn btn-default' do %>
  <%= fa_icon('arrow-left') %>
<% end %>

app/views/trainings/show.html.erb
<h1><%= @training %></h1>

<div class="row">
  <div class="col-xs-12 col-md-6">
    <h4>Categoría</h4>
    <p><%= @training.category %></p>

    <% if @training.objective.present? %>
      <h4>Objetivo</h4>
      <p><%= @training.objective %></p>
    <% end %>

    <h4>Sede</h4>
    <p><%= @training.company %></p>

    <% if @training.area_id.present? %>
      <h4>Área responsable</h4>
      <p><%= @aide %></p>
    <% end %>

    <% if @training.collaborator_id.present? %>
      <h4>Colaborador responsable</h4>
      <p><%= @aide %></p>
    <% end %>

    <h4>Fecha</h4>
    <p><%= @training.date.strftime('%d/%m/%y %R') %></p>

    <h4>Intensidad horaria</h4>
    <p><%= @training.hourly_intensity %></p>

    <h4>Formador</h4>
    <p><%= @training.trainer %></p>

    <h4><%= @training.internal ? 'Formación interna' : 'Formación externa' %></h4>
  </div>
  <div class="col xs-12 col-md-6">
    <h4>Ejecuciones de la formación</h4>
    <div class="table-responsive overflowing-box-tall">
      <table class="table table-responsive table-condensed">
        <tbody>
          <% @training.training_executions.each do |training_execution| %>
            <tr>
              <td>
                <p><%= training_execution %> (<%= training_execution.category %>)</p>
                <p><%= training_execution.date.strftime('%d/%m/%y %R') %></p>
              </td>
              <td>
                <span class="pull-right">
                  <%= link_to training_execution, class: 'btn btn-info' do %>
                    <%= fa_icon('info') %>
                  <% end %>
                </span>
              </td>
            </tr>
          <% end %>
          <% if @training.training_executions.empty? %>
            <tr>
              <td>No se encontraron ejecuciones para esta formación</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div>
  <div class="btn-group" role="group">
    <%= link_to trainings_path, class: 'btn btn-default' do %>
      <%= fa_icon('arrow-left') %>
    <% end %>
    <%= link_to new_training_execution_path(training_id: @training.id), class: 'btn btn-default' do %>
      Registrar ejecución
    <% end %>
  </div>
  <%= link_to edit_training_path(@training), class: 'btn btn-warning pull-right' do %>
    <%= fa_icon('pencil') %>
  <% end %>
</div>