config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'employees#index'
  resources :trainings do
    collection do
      get :all
    end
  end
  resources :training_executions do
    member do
      get :register_attendances
      patch :save_attendances
    end
  end
  resources :employees
  resources :companies
  resources :areas
end

app/models/employee.rb
class Employee < ApplicationRecord
  FILTER_OPTIONS = [
    %w[Nombre name],
    %w[Identificación identification],
    %w[Posición position],
    %w[Fecha\ de\ ingreso admission_date],
    %w[Área area_id],
    %w[Compañía company_id],
    %w[Sin\ capacitaciones without_trainings]
  ].freeze

  has_many :attendances
  has_many :training_executions, through: :attendances
  has_many :planned_trainings, foreign_key: :collaborator_id, class_name: Training
  has_many :trainings_given, foreign_key: :collaborator_id, class_name: TrainingExecution

  belongs_to :area
  belongs_to :company

  validates :name, presence: true
  validates :identification, uniqueness: true, numericality: { greater_than: 0 }
  validates :admission_date, presence: true

  scope :by_name, (->(name) { where('name like ?', "%#{name}%") })
  scope :by_identification, (->(identification) { where identification: identification })
  scope :by_position, (->(position) { where('position like ?', "%#{position}%") })
  scope :by_area, (->(area_id) { where(area_id: area_id) })
  scope :by_company, (->(company_id) { where company_id: company_id })
  scope :active, (-> { where active: true })
  scope :by_admission_date, (->(initial_date, final_date) { where(admission_date: initial_date..final_date) })
  scope :without_trainings_between_dates, (->(initial_date, final_date) { where.not(id: joins(:training_executions).where(training_executions: { date: initial_date..final_date }).select(:id).distinct) })

  def self.filter_employees(params)
    @employees = Employee.all
    @employees = @employees.by_name(params[:name]) if params[:name].present?
    @employees = @employees.by_identification(params[:identification]) if params[:identification].present?
    @employees = @employees.by_position(params[:position]) if params[:position].present?
    @employees = @employees.by_area(params[:area_id]) if params[:area_id].present?
    @employees = @employees.by_company(params[:company_id]) if params[:company_id].present?
    @employees = @employees.active if params[:active]
    @employees = @employees.by_admission_date(params[:initial_date].to_time, params[:final_date].to_time) if params[:initial_date].present? && params[:final_date].present?
    @employees = @employees.without_trainings_between_dates(params[:trainings_initial_date].to_time, params[:trainings_final_date].to_time) if params[:trainings_initial_date].present? && params[:trainings_final_date].present?
    @employees
  end

  def to_s
    "#{name} (C.C. #{identification})"
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    gon.areas = Area.all
    gon.companies = Company.all
    @employees = Employee.filter_employees(params)
    @employees = @employees.paginate(page: params[:page])
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'El empleado fue creado exitósamente.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'El empleado fue actualizado exitósamente.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'El empleado fue eliminado exitósamente.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    params.require(:employee).permit(:name, :identification, :area_id, :admission_date, :active, :position, :company_id)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2><%= pluralize(employee.errors.count, 'error') %> no permitieron guardar el empleado:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :identification, 'Identificación (C.C.)' %>
    <%= f.number_field :identification, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :position, 'Posición' %>
    <%= f.text_field :position, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :area_id, 'Área' %>
    <%= f.collection_select :area_id, Area.all, :id, :name, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :company_id, 'Compañía' %>
    <%= f.collection_select :company_id, Company.all, :id, :name, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :admission_date, 'Fecha de ingreso' %>
    <div class="input-group date" id="datetimepicker">
      <%= f.text_field :admission_date, required: true, value: employee.admission_date.present? ? employee.admission_date.strftime('%d/%m/%y') : '', class: 'form-control' %>
      <span class="input-group-addon">
        <%= fa_icon('calendar') %>
      </span>
    </div>
  </div>

  <div class="checkbox">
    <%= f.label :active do %>
      <%= f.check_box :active %> Activo
    <% end %>
  </div>

  <div class="actions">
    <%= link_to employees_path, class: 'btn btn-default' do %>
      <%= fa_icon('arrow-left') %> Empleados
    <% end %>
    <%= f.submit 'Guardar', class: 'btn btn-default pull-right' %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editando al empleado <%= @employee %></h1>

<div>
  <%= render 'form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<h1>Empleados</h1>

<div class="margin-bottom" style="display: none;" id="filters">
  <%= form_tag employees_path, method: :get do %>
    <div class="form-group">
      <%= text_field_tag :name, params[:name], placeholder: 'Filtrar por nombre...', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= number_field_tag :identification, params[:identification], placeholder: 'Filtrar por identificación...', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= text_field_tag :position, params[:position], placeholder: 'Filtrar por posición...', class: 'form-control' %>
    </div>

    <div class="row margin-bottom">
      <div class="col-md-6">
        <div class="input-group date" id="initial-date-picker">
          <%= text_field_tag :trainings_initial_date, params[:trainings_initial_date], placeholder: 'Sin capacitaciones entre el...', class: 'form-control' %>
          <span class="input-group-addon">
            <%= fa_icon('calendar') %>
          </span>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-group date" id="final-date-picker">
          <%= text_field_tag :trainings_final_date, params[:trainings_final_date], placeholder: 'Y el...', class: 'form-control' %>
          <span class="input-group-addon">
            <%= fa_icon('calendar') %>
          </span>
        </div>
      </div>
    </div>

    <div class="row margin-bottom">
      <div class="col-md-6">
        <div class="input-group date" id="initial-date-picker">
          <%= text_field_tag :initial_date, params[:initial_date], placeholder: 'Fecha de admisión entre el...', class: 'form-control' %>
          <span class="input-group-addon"><%= fa_icon('calendar') %></span>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-group date" id="final-date-picker">
          <%= text_field_tag :final_date, params[:final_date], placeholder: 'Y el...', class: 'form-control' %>
          <span class="input-group-addon"><%= fa_icon('calendar') %></span>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= select_tag :area_id, content_tag(:option, 'Filtrar por área...', value: '') + options_from_collection_for_select(Area.all, :id, :name, params[:area_id]), class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= select_tag :company_id, content_tag(:option, 'Filtrar por compañía...', value: '') + options_from_collection_for_select(Company.all, :id, :name, params[:company_id]), class: 'form-control' %>
    </div>

    <div class="form-group">
      <div class="checkbox">
        <label><%= check_box_tag :active, true, params[:active].present? %> Sólo empleados activos</label>
      </div>
    </div>

    <div>
      <%= link_to 'Quitar filtros', employees_path, class: 'btn btn-default' %>
      <%= button_tag type: :submit, class: 'btn btn-default pull-right' do %>
        <%= fa_icon('search') %> Filtrar
      <% end %>
    </div>
  <% end %>
</div>

<div class="margin-bottom" id="no-filters">
  <%= button_tag 'Aplicar filtros', onclick: 'showFilters()', class: 'btn btn-default' %>
</div>

<div class="table-responsive">
  <table class="table table-striped">
    <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td>
          <h4><%= employee %> <%= raw '<small>(Inactivo)</small>' unless employee.active %></h4>
          <p><%= employee.area %> (<%= employee.position %>)</p>
          <p><%= employee.company %></p>
        </td>
        <td>
          <span class="pull-right">
            <%= link_to employee, class: 'btn btn-info' do %>
              <%= fa_icon('info') %>
            <% end %>
            <%= link_to edit_employee_path(employee), class: 'btn btn-warning' do %>
              <%= fa_icon('pencil') %>
            <% end %>
            <%= link_to employee, method: :delete, data: { confirm: '¿Seguro que desea eliminar el empleado?' }, class: 'btn btn-danger' do %>
              <%= fa_icon('trash') %>
            <% end %>
          </span>
        </td>
      </tr>
    <% end %>
    <% if @employees.empty? %>
      <tr>
        <td>
          No se encontraron registros
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div>
  <%= link_to new_employee_path, class: 'btn btn-default' do %>
      <%= fa_icon('plus') %>
  <% end %>
</div>

<%= will_paginate @employees %>

app/views/employees/new.html.erb
<h1>Nuevo empleado</h1>

<div class="margin-bottom">
  <%= render 'form', employee: @employee %>
</div>

app/views/employees/show.html.erb
<h1><%= @employee.name %></h1>

<div class="row">
  <div class="col-xs-12 col-md-6">
    <h4>Identificación</h4>
    <p>C.C. <%= @employee.identification %></p>

    <h4>Área</h4>
    <p><%= @employee.area %></p>

    <h4>Cargo</h4>
    <p><%= @employee.position %></p>

    <h4>Compañía</h4>
    <p><%= @employee.company %></p>

    <h4>Fecha de ingreso</h4>
    <p><%= @employee.admission_date %></p>

    <h4>Estado</h4>
    <p><%= @employee.active ? 'Activo' : 'Inactivo' %></p>
  </div>

  <div class="col-xs-12 col-md-6">
    <h4>Capacitaciones</h4>
    <div class="table-responsive overflowing-box-tall">
      <table class="table table-striped table-condensed">
        <tbody>
          <% @employee.training_executions.each do |training_execution| %>
            <tr>
              <td>
                <p><%= training_execution %> (<%= training_execution.category %>)</p>
                <p><%= training_execution.date.strftime('%d/%m/%y %R') %></p>
              </td>
              <td>
                <span class="pull-right">
                  <%= link_to training_execution_path(training_execution), class: 'btn btn-info' do %>
                    <%= fa_icon('info') %>
                  <% end %>
                </span>
              </td>
            </tr>
          <% end %>
          <% if @employee.training_executions.empty? %>
            <tr>
              <td>El empleado no ha tenido capacitaciones</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div>
  <%= link_to employees_path, class: 'btn btn-default' do %>
    <%= fa_icon('arrow-left') %>
  <% end %>
  <%= link_to edit_employee_path(@employee), class: 'btn btn-warning pull-right' do %>
    <%= fa_icon('pencil') %>
  <% end %>
</div>