config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'employees#index'
  resources :trainings do
    collection do
      get :all
    end
  end
  resources :training_executions do
    member do
      get :register_attendances
      patch :save_attendances
    end
  end
  resources :employees
  resources :companies
  resources :areas
end

app/models/training_execution.rb
class TrainingExecution < ApplicationRecord
  has_many :attendances
  has_many :employees, through: :attendances

  belongs_to :company

  validates :category, presence: true
  validates :topic, presence: true
  validates :date, presence: true
  validates :hourly_intensity, numericality: { greater_than_or_equal_to: 0 }
  validates :trainer, presence: true

  scope :by_category, (->(category) { where('category like ?', "%#{category}%") })
  scope :by_topic, (->(topic) { where('topic like ?', "%#{topic}%") })
  scope :by_date, (->(initial_date, final_date) { where(date: initial_date..final_date) })
  scope :by_area, (->(area_id) { where(area_id: area_id) })
  scope :by_collaborator, (->(collaborator) { where(collaborator_id: Employee.by_name(collaborator).select(:id)) })
  scope :by_company, (->(company_id) { where(company_id: company_id) })
  scope :planned, (-> { where(planned: true) })

  def self.filter_training_executions(params)
    @training_executions = TrainingExecution.all
    @training_executions = @training_executions.by_category(params[:category]) if params[:category].present?
    @training_executions = @training_executions.by_topic(params[:topic]) if params[:topic].present?
    @training_executions = @training_executions.by_date(params[:initial_date].to_time, params[:final_date].to_time) if params[:initial_date].present? && params[:final_date].present?
    @training_executions = @training_executions.by_area(params[:area_id]) if params[:area_id].present?
    @training_executions = @training_executions.by_collaborator(params[:collaborator]) if params[:collaborator].present?
    @training_executions = @training_executions.by_company(params[:company_id]) if params[:company_id].present?
    @training_executions = @training_executions.planned if params[:planned].present?
    @training_executions
  end

  def save_attendances(employees_id)
    attendances.destroy_all
    employees_id ||= []
    employees_id.each do |employee_id|
      attendances.create(employee: Employee.find(employee_id))
    end
  end

  def to_s
    topic
  end
end

app/controllers/training_executions_controller.rb
class TrainingExecutionsController < ApplicationController
  before_action :set_training_execution, only: [:show, :edit, :update, :destroy, :register_attendances, :save_attendances]

  # GET /training_executions
  # GET /training_executions.json
  def index
    gon.areas = Area.all
    gon.companies = Company.all
    @training_executions = TrainingExecution.filter_training_executions(params)
    @training_executions = @training_executions.paginate(page: params[:page])
  end

  # GET /training_executions/1
  # GET /training_executions/1.json
  def show
    @aide = if @training_execution.area_id.present?
              Area.find(@training_execution.area_id)
            elsif @training_execution.collaborator_id.present?
              Employee.find(@training_execution.collaborator_id)
            end
  end

  # GET /training_executions/new
  def new
    if params[:training_id].present?
      @training_execution = TrainingExecution.new(Training.find(params[:training_id]).attributes)
      @training_execution.planned = true
      @training_execution.training_id = params[:training_id]
    else
      @training_execution = TrainingExecution.new
    end
  end

  # GET /training_executions/1/edit
  def edit
  end

  # POST /training_executions
  # POST /training_executions.json
  def create
    @training_execution = TrainingExecution.new(training_execution_params)

    respond_to do |format|
      if @training_execution.save
        format.html { redirect_to @training_execution, notice: 'La ejecución de la formación fue creada exitósamente.' }
        format.json { render :show, status: :created, location: @training_execution }
      else
        format.html { render :new }
        format.json { render json: @training_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /training_executions/1
  # PATCH/PUT /training_executions/1.json
  def update
    respond_to do |format|
      if @training_execution.update(training_execution_params)
        format.html { redirect_to @training_execution, notice: 'La ejecución de la formación fue actualizada exitósamente.' }
        format.json { render :show, status: :ok, location: @training_execution }
      else
        format.html { render :edit }
        format.json { render json: @training_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_executions/1
  # DELETE /training_executions/1.json
  def destroy
    @training_execution.destroy
    respond_to do |format|
      format.html { redirect_to training_executions_url, notice: 'La ejecución de la formación fue eliminada exitósamente.' }
      format.json { head :no_content }
    end
  end

  def register_attendances
    @employees = Employee.where.not(id: @training_execution.employees.ids)
    @selected_employees = @training_execution.employees
  end

  def save_attendances
    @training_execution.save_attendances(params[:employees_id])
    respond_to do |format|
      if @training_execution.save
        format.html { redirect_to @training_execution, notice: 'Se registró exitósamente las asistencias a la formación ejecutada.' }
        format.json { render :show, status: :ok, location: @training_execution }
      else
        format.html { render :register_attendances }
        format.json { render json: @training_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_training_execution
    @training_execution = TrainingExecution.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def training_execution_params
    params.require(:training_execution).permit(:category, :topic, :objective, :date, :hourly_intensity, :trainer, :internal, :area_id, :collaborator_id, :company_id, :training_id, :planned)
  end
end

app/helpers/training_executions_helper.rb
module TrainingExecutionsHelper
end

app/views/training_executions/_form.html.erb
<%= form_for(training_execution) do |f| %>
  <% if training_execution.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2><%= pluralize(training_execution.errors.count, 'error') %> no permitieron guardar la formación:</h2>

      <ul>
        <% training_execution.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category, 'Tipo' %>
    <%= f.select :category, options_for_select(Training::CATEGORIES, training_execution.category.blank? || Training::CATEGORIES.include?(training_execution.category) ? Training::CATEGORIES[0] : Training::CATEGORIES[3]), {}, onchange: 'trainingExecutionCategoryChanged()', class: 'form-control' %>
  </div>

  <div class="form-group" id="category_form_group" style="<%= 'display: none;' if training_execution.category.blank? || Training::CATEGORIES.include?(training_execution.category) %>">
    <%= f.label :category, '¿Cuál?' %>
    <input class="form-control" type="text" value="<%= training_execution.category %>" <%= 'name=training_execution[category]' unless training_execution.category.blank? || Training::CATEGORIES.include?(training_execution.category) %> id="training_category_other">
  </div>

  <div class="form-group">
    <%= f.label :topic, 'Tema' %>
    <%= f.text_field :topic, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :objective, 'Objetivo' %>
    <%= f.text_area :objective, rows: 4, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label style="display: block;">Responsable</label>
    <label class="radio-inline"><input type="radio" name="attendant" onchange="trainingExecutionAttendantChanged()" value="area" <%= 'checked' if training_execution.area_id.present? || (training_execution.area_id.blank? && training_execution.collaborator_id.blank?) %>>Área</label>
    <label class="radio-inline"><input type="radio" name="attendant" onchange="trainingExecutionAttendantChanged()" value="collaborator" <%= 'checked' if training_execution.collaborator_id.present? %>>Colaborador</label>
  </div>

  <div class="form-group" id="area_form_group" style="<%= 'display: none;' if training_execution.collaborator_id.present? %>">
    <%= f.label :area_id, 'Área responsable' %>
    <%= f.collection_select :area_id, Area.all, :id, :name, { include_blank: 'Seleccionar área...' }, { class: 'form-control' } %>
  </div>

  <div class="form-group" id="collaborator_form_group" style="<%= 'display: none;' if training_execution.area_id.present? || training_execution.collaborator_id.blank? && training_execution.area_id.blank? %>">
    <%= f.label :area_id, 'Colaborador responsable' %>
    <%= f.collection_select :collaborator_id, Employee.all, :id, :name, { include_blank: 'Seleccionar colaborador...' }, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :company_id, 'Compañía' %>
    <%= f.collection_select :company_id, Company.all, :id, :name, {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :date, 'Fecha de realización' %>
    <div class="input-group date" id="datetimepicker">
      <%= f.text_field :date, required: true, value: training_execution.date.present? ? training_execution.date.strftime('%d/%m/%y %R') : '', class: 'form-control' %>
      <span class="input-group-addon">
        <%= fa_icon('calendar') %>
      </span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :hourly_intensity, 'Intensidad horaria' %>
    <%= f.number_field :hourly_intensity, min: 0, step: :any, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :trainer, 'Formador' %>
    <%= f.text_field :trainer, required: true, class: 'form-control' %>
  </div>

  <div class="checkbox">
    <%= f.label :internal do %>
      <%= f.check_box :internal %>Interno
    <% end %>
  </div>

  <%= f.hidden_field :planned, value: training_execution.planned %>

  <%= f.hidden_field :training_id, value: training_execution.training_id %>

  <div class="actions">
    <%= f.submit 'Guardar', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/training_executions/edit.html.erb
<h1>Editando formación ejecutada</h1>

<div class="margin-bottom">
  <%= render 'form', training_execution: @training_execution %>
</div>

<%= link_to training_executions_path, class: 'btn btn-default' do %>
  <%= fa_icon('arrow-left') %>
<% end %>
<%= link_to @training_execution, class: 'btn btn-info pull-right' do %>
  <%= fa_icon('info') %>
<% end %>

app/views/training_executions/index.html.erb
<h1>Formaciones ejecutadas</h1>

<div class="row">
  <%= form_tag training_executions_path, method: :get do %>
    <div class="col-xs-12 col-md-8">
      <div class="form-group" id="filters">
        <%= select_tag :category, options_for_select(Training::CATEGORIES, params[:category].blank? || Training::CATEGORIES.include?(params[:category]) ? params[:category] : Training::CATEGORIES[3]), onchange: 'trainingsFilterCategoryChanged()', class: 'form-control' if params[:filter].blank? || params[:filter] == 'category' %>
        <%= text_field_tag :topic, params[:topic], placeholder: 'Filtrar por...', class: 'form-control' if params[:filter] == 'topic' %>
        <% if params[:filter] == 'date' %>
          <div class="row">
            <div class="col-md-6">
              <div class="input-group date" id="initial-date-picker">
                <%= text_field_tag :initial_date, params[:initial_date], placeholder: 'Fecha inicial', class: 'form-control' %>
                <span class="input-group-addon">
                  <%= fa_icon('calendar') %>
                </span>
              </div>
            </div>
            <div class="col-md-6">
              <div class="input-group date" id="final-date-picker">
                <%= text_field_tag :final_date, params[:final_date], placeholder: 'Fecha final', class: 'form-control' %>
                <span class="input-group-addon">
                  <%= fa_icon('calendar') %>
                </span>
              </div>
            </div>
          </div>
        <% end %>
        <%= select_tag :area_id, options_from_collection_for_select(Area.all, :id, :name, params[:area_id]), class: 'form-control' if params[:filter] == 'area_id' %>
        <%= text_field_tag :collaborator, params[:collaborator], placeholder: 'Filtrar por nombre de colaborador...', class: 'form-control' if params[:filter] == 'collaborator' %>
        <%= select_tag :company_id, options_from_collection_for_select(Company.all, :id, :name, params[:company_id]), class: 'form-control' if params[:filter] == 'company_id' %>
      </div>
      <div class="form-group" id="category_form_group" style="<%= 'display: none;' if params[:category].blank? || Training::CATEGORIES.include?(params[:category]) %>">
        <input class="form-control" type="text" value="<%= params[:category] %>" <%= 'name=category' unless params[:category].blank? || Training::CATEGORIES.include?(params[:category]) %> placeholder="¿Cuál?" id="category_other">
      </div>
      <div class="form-group">
        <div class="checkbox">
          <label><%= check_box_tag :planned, true, params[:planned].present? %> Sólo formaciones planeadas</label>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-3">
      <div class="form-group">
        <%= select_tag :filter, options_for_select(Training::FILTER_OPTIONS, params[:filter]), onchange: 'trainingsFilterChanged()', class: 'form-control' %>
      </div>
    </div>
    <div class="col-xs-12 col-md-1">
      <%= submit_tag 'Filtrar', class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

<div class="table-responsive margin-bottom">
  <table class="table table-striped">
    <tbody>
    <% @training_executions.each do |training_execution| %>
      <tr>
        <td>
          <p><%= training_execution %> (<%= training_execution.category %>)</p>
          <p><%= training_execution.date.strftime('%d/%m/%y %R') %></p>
        </td>
        <td>
          <span class="pull-right">
            <%= link_to training_execution, class: 'btn btn-info' do %>
              <%= fa_icon('info') %>
            <% end %>
            <%= link_to edit_training_execution_path(training_execution), class: 'btn btn-warning' do %>
              <%= fa_icon('pencil') %>
            <% end %>
            <%= link_to training_execution, method: :delete, data: { confirm: '¿Seguro que desea eliminar la formación?' }, class: 'btn btn-danger' do %>
              <%= fa_icon('trash') %>
            <% end %>
          </span>
        </td>
      </tr>
    <% end %>
    <% if @training_executions.empty? %>
      <tr>
        <td>
          No se encontraron registros
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div>
  <%= link_to new_training_execution_path, class: 'btn btn-default' do %>
    <%= fa_icon('plus') %>
  <% end %>

  <%= link_to all_trainings_path, class: 'btn btn-default pull-right' do %>
    <%= fa_icon('eye') %> Todas las formaciones
  <% end %>
</div>

<%= will_paginate @training_executions %>

app/views/training_executions/new.html.erb
<h1>Nueva formación ejecutada</h1>

<div class="margin-bottom">
  <%= render 'form', training_execution: @training_execution %>
</div>

<%= link_to training_executions_path, class: 'btn btn-default' do %>
  <%= fa_icon('arrow-left') %>
<% end %>

app/views/training_executions/register_attendances.html.erb
<h1>Registrar asistencias a la formación</h1>

<div class="margin-bottom">
  <%= form_for @training_execution, url: save_attendances_training_execution_path do |f| %>
    <div class="row">
      <div class="col-md-6 col-xs-11">
        <div class="form-group input-group">
          <input type="text" placeholder="Filtrar empleados..." onkeyup="filterEmployees()" class="form-control" id="employees-filter">
          <span class="input-group-addon"><%= fa_icon('search') %></span>
        </div>
        <div class="list-group overflowing-box" id="non-selected-employees">
          <% @employees.each do |employee| %>
            <button type="button" onclick="selectEmployee(this, <%= employee.id %>, '<%= employee %>')" class="list-group-item list-group-item-compact"><%= employee %></button>
          <% end %>
        </div>
      </div>
      <div class="col-md-1 col-xs-1">
        <div class="margin-bottom">
          <button type="button" onclick="addEmployee()" class="btn btn-default full-width"><%= fa_icon('angle-right') %></button>
        </div>
        <div class="margin-bottom">
          <button type="button" onclick="removeEmployee()" class="btn btn-default full-width"><%= fa_icon('angle-left') %></button>
        </div>
      </div>
      <div class="col-md-5 col-xs-12">
        <div class="list-group overflowing-box" id="selected-employees">
          <% @selected_employees.each do |employee| %>
            <button type="button" onclick="selectEmployee(this, <%= employee.id %>, '<%= employee %>')" class="list-group-item list-group-item-compact"><%= employee %></button>
          <% end %>
        </div>
        <div id="hidden-inputs">
          <% @selected_employees.each do |employee| %>
            <%= hidden_field_tag 'employees_id[]', employee.id, id: "employee-#{employee.id}" %>
          <% end %>
        </div>
      </div>
    </div>
    <%= f.submit value: 'Guardar', class: 'btn btn-default' %>
  <% end %>

</div>

<%= link_to training_executions_path, class: 'btn btn-default' do %>
  <%= fa_icon('arrow-left') %>
<% end %>
<%= link_to @training_execution, class: 'btn btn-info pull-right' do %>
  <%= fa_icon('info') %>
<% end %>

app/views/training_executions/show.html.erb
<h1><%= @training_execution %></h1>

<div class="row">
  <div class="col-xs-12 col-md-6">
    <h4>Categoría</h4>
    <p><%= @training_execution.category %></p>

    <% if @training_execution.objective.present? %>
      <h4>Objetivo</h4>
      <p><%= @training_execution.objective %></p>
    <% end %>

    <h4>Sede</h4>
    <p><%= @training_execution.company %></p>

    <% if @training_execution.area_id.present? %>
      <h4>Área responsable</h4>
      <p><%= @aide %></p>
    <% end %>

    <% if @training_execution.collaborator_id.present? %>
      <h4>Colaborador responsable</h4>
      <p><%= @aide %></p>
    <% end %>

    <h4>Fecha</h4>
    <p><%= @training_execution.date.strftime('%d/%m/%y %R') %></p>

    <h4>Intensidad horaria</h4>
    <p><%= @training_execution.hourly_intensity %></p>

    <h4>Formador</h4>
    <p><%= @training_execution.trainer %></p>

    <h4><%= @training_execution.internal ? 'Formación interna' : 'Formación externa' %></h4>

    <h4><%= @training_execution.planned ? 'Formación planeada' : 'Formación no planeada' %></h4>
  </div>
  <div class="col-xs-12 col-md-6">
    <h4>Asistentes</h4>
    <div class="table-responsive overflowing-box-tall">
      <table class="table table-striped table-condensed">
        <tbody>
          <% @training_execution.employees.each do |employee| %>
            <tr>
              <td>
                <p><%= employee %> <%= raw '<small>(Inactivo)</small>' unless employee.active %></p>
                <p><%= employee.area %> (<%= employee.position %>)</p>
              </td>
              <td>
                <span class="pull-right">
                  <%= link_to employee, class: 'btn btn-info' do %>
                    <%= fa_icon('info') %>
                  <% end %>
                </span>
              </td>
            </tr>
          <% end %>
          <% if @training_execution.employees.empty? %>
            <tr>
              <td>La capacitación no tuvo asistentes</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to register_attendances_training_execution_path, class: 'btn btn-default' do %>
      Modificar asistencias
    <% end %>
  </div>
</div>

<div class="btn-group" role="group">
  <%= link_to training_executions_path, class: 'btn btn-default' do %>
    <%= fa_icon('arrow-left') %>
  <% end %>
  <%= link_to register_attendances_training_execution_path(@training_execution), class: 'btn btn-default' do %>
    Registrar asistencias
  <% end %>
</div>
<%= link_to edit_training_execution_path(@training_execution), class: 'btn btn-warning pull-right' do %>
  <%= fa_icon('pencil') %>
<% end %>