config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'employees#index'
  resources :trainings do
    collection do
      get :all
    end
  end
  resources :training_executions do
    member do
      get :register_attendances
      patch :save_attendances
    end
  end
  resources :employees
  resources :companies
  resources :areas
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmpTracker 2.0</title>
    <%= csrf_meta_tags %>
    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-action="<%= action_name %>" data-controller="<%= controller_name %>">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
            <span><%= fa_icon('bars', class: 'fa-lg') %></span>
          </button>
          <a class="navbar-brand" href="#">Emp-Tracker</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Formaciones', all_trainings_path %></li>
            <li><%= link_to 'Empleados', employees_path %></li>
            <li><%= link_to 'Áreas', areas_path %></li>
            <li><%= link_to 'Compañias', companies_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if admin_signed_in? %>
              <li><%= link_to('Logout', destroy_admin_session_path, method: :delete) %></li>
            <% else %>
              <li><%= link_to('Login', new_admin_session_path)  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% if notice.present? %>
        <div class="alert alert-info alert-dismissable fade in">
          <a href="#" class="close" data-dismiss="alert" aria-label="close"><%= fa_icon('times-circle') %></a>
          <%= notice %>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="alert alert-warning alert-dismissable fade in">
          <a href="#" class="close" data-dismiss="alert" aria-label="close"><%= fa_icon('times-circle') %></a>
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <footer class="footer-distributed">
      <div class="container">
        <p class="footer-links">Made by Carlos Felipe Agudelo</p>
        <p>cf.agudelo96@gmail.com</p>
        <%= link_to 'https://www.linkedin.com/in/carlos-agudelo-3b232a104/?locale=en_US', class: 'footer-link-icon' do %>
          <%= fa_icon('linkedin') %>
        <% end %>
        <%= link_to 'https://github.com/cfagudelo96', class: 'footer-link-icon' do %>
          <%= fa_icon('github') %>
        <% end %>
      </div>
    </footer>
  </body>
</html>